ExpertAssessment.WebUI/Controllers/EvaluationController.cs
using ExpertAssessment.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpertAssessment.WebUI.Controllers
{
    public class EvaluationController : Controller
    {
        //
        // GET: /Evaluation/
        private IAhpRepository _repository;

        public EvaluationController(IAhpRepository evaluationRepository)
        {
            this._repository = evaluationRepository;
        }
        public ViewResult Matrix()
        {
            return View(_repository.AllEvaluations());
        }

    }
}

ExpertAssessment.WebUI/Controllers/HierarchyController.cs
using ExpertAssessment.Domain.Concrete;
using ExpertAssessment.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using ExpertAssessment.WebUI.Infrastructure;

namespace ExpertAssessment.WebUI.Controllers
{

    public class HttpParamActionAttribute : ActionNameSelectorAttribute
    {
        public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo)
        {
            if (actionName.Equals(methodInfo.Name, StringComparison.InvariantCultureIgnoreCase))
                return true;

            if (!actionName.Equals("Action", StringComparison.InvariantCultureIgnoreCase))
                return false;

            var request = controllerContext.RequestContext.HttpContext.Request;
            return request[methodInfo.Name] != null;
        }
    }



    public class HierarchyController : Controller
    {


        //
        // GET: /NewHierarchy/
        private AHPRepository _repository;
        
        //private List<string> _characteristicList = new List<string>() {"o","la","la" };
        private RepositoryHelper _helper = new RepositoryHelper(); 


        public HierarchyController()
        {
            _repository = new AHPRepository();
        }

        public ActionResult CreateNewHierarchy()
        {
            var model = new NewHierarchyModel();

            return View(model);
        }

        [HttpPost]
        [HttpParamAction]
        public ActionResult AddNewLevel(NewHierarchyModel model, int levelIndex) 
        {
            var level = new LevelCharacteristicModel
                {
                    Id = levelIndex,
                    Values = new List<string> { "" }
                };

            model.LevelCharacteristics.Add(level);

            return View("CreateNewHierarchy", model);
        }

        //[HttpParamAction]
        //public ActionResult AddNewCharacteristic(NewHierarchyModel model, int levelIndex) 
        //{
        //    var level = model.LevelCharacteristics.FirstOrDefault(x => x.Id == levelIndex);

        //    if (level != null)
        //        level.Values.Add("");

        //    return PartialView(level);
        //}

        [HttpPost]
        [HttpParamAction]    
        public ActionResult Save(NewHierarchyModel model)
        {
            var h = _repository.AddHierarchy(model.HierarchyTitle, model.HierarchyGoal,
               _helper.ToCharacteristics(model.LevelCharacteristics));
            
            //_repository.AddGoal(h, model.HierarchyGoal);


            return View("MadedHierarchy", model);
        }

        public ActionResult MadedHierarchy(NewHierarchyModel model) 
        {
            return View(model);
        }

        //[HttpPost]
        [HttpParamAction]    
        public ActionResult AddNewLevel(NewHierarchyModel model) // don't know how to take parameter index
        {
            //var h = _repository.AddHierarchy(model.HierarchyTitle);
            //_repository.AddGoal(h, model.HierarchyGoal);
            //_repository.AddAction(User.Identity.Name, model.HierarchyTitle);
            //model.HierarchyLevels.Add(index);
            model.LevelCharacteristics.Add(new LevelCharacteristicModel() 
            { 
                Id = model.LevelCharacteristics.Count + 2, 
                Values = new List<string> { "" } 
            });
            return View("CreateNewHierarchy", model);
        }

        [HttpPost]
        [HttpParamAction]    
        public ActionResult AddNewCharacteristic(NewHierarchyModel model, int levelIndex = 2) 
        {
            //model.LevelCharacteristics[levelIndex].Add(characteristicName);
            //model.LevelCharacteristics[levelIndex].Values.Add(characteristicName);
            
            var level = model.LevelCharacteristics.FirstOrDefault(x => x.Id == levelIndex);
            if (level != null)
            {
                level.Values.Add("");                
            }

            return View("CreateNewHierarchy", model);
        }
    }
}

ExpertAssessment.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href ="@Url.Content("~/Content/bootstrap.min.css")" rel ="stylesheet" type ="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>

    @RenderSection("JS", false)

</head>

<body>

    <div class="row">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav affix" data-offset-top="200" style="margin-left: 1.5%; margin-top: 7.7%;">
                <li>
                    <a href="@Url.Action("CreateNewHierarchy", "Hierarchy")">Create new hierarchy
                        @*<i class="icon-chevron-right"></i>*@
                    </a>
                </li>

                <li>
                    <a href="#">Modify hierarchy
                        @*<i class="icon-chevron-right"></i>*@
                    </a>
                </li>



                <li>
                    <a href ="#">Expert Assessment
                            @*<i class="icon-chevron-right"></i>*@
                    </a>
                </li>
                <li>
                    <a href ="#">Detale analisys
                            @*<i class="icon-chevron-right"></i>*@
                    </a>
                </li>
                <li>
                    <a href ="#">Results
                            @*<i class="icon-chevron-right"></i>*@
                    </a>
                </li>
            </ul>
        </div>
    </div>

   

    <div class="navbar">
        <div class="navbar-inner" style="-webkit-border-radius: 0; -moz-border-radius: 0; border-radius: 0;">
            <div class="container">
                <ul class="nav">
                    <li class="active">@Html.ActionLink("AHP", "Index", "Account")</li>
                    <li>@Html.ActionLink("What is it?", "Eval", "Evaluation")    </li>
                    <li>@Html.ActionLink("How is it work?", "Eval", "Evaluation")</li>
                    <li>@Html.ActionLink("Expert assessment", "Eval", "Evaluation")</li>
                    <li>@Html.ActionLink("Process mathematic tools ", "Eval", "Evaluation")</li>
                </ul>
            </div>
        </div>

    </div>
    @*<div class="row">
        <div class="span9">*@
    @RenderBody()
    @*</div>
    </div>*@
    
    
</body>
<//html>